# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8379959b-1d18-4ba2-9a12-d6177a5cf7ea";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" "noatime" "space_cache=v2" "ssd" "discard=async" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/8379959b-1d18-4ba2-9a12-d6177a5cf7ea";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:3" "noatime" "space_cache=v2" "ssd" "discard=async" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8379959b-1d18-4ba2-9a12-d6177a5cf7ea";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" "noatime" "space_cache=v2" "ssd" "discard=async" ];
      neededForBoot = true;
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/8379959b-1d18-4ba2-9a12-d6177a5cf7ea";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd:3" "noatime" "space_cache=v2" "ssd" "discard=async" ];
      neededForBoot = true;
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/8379959b-1d18-4ba2-9a12-d6177a5cf7ea";
      fsType = "btrfs";
      options = [ "subvol=@persist" "compress=zstd:3" "noatime" "space_cache=v2" "ssd" "discard=async" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2DC4-3300";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
