# Global
windowrule = suppress_event maximize, match:class .*

# Floating utilities
windowrule = float on, match:class ^(pavucontrol|org.pulseaudio.pavucontrol|imv|org.gnome.FileRoller)$

# Thunar
windowrule = float on,     match:class ^(thunar)$
windowrule = size 70% 70%, match:class ^(thunar)$
#windowrule = center,       match:class ^(thunar)$

# PiP / Meet (title match still works)
windowrule = float on, match:title ^(Picture-in-Picture|Google Meet|Meet - .*)$
windowrule = pin on,   match:title ^(Picture-in-Picture)$

# Layerrules (go in extraConfig)
layerrule = blur on, match:namespace logout_dialog

layerrule {
    name = noctalia-blur
    match:namespace = noctalia-background-.*
    ignore_alpha = 0.35
    blur = on
}
